# LinuxCNC config for PrintNC on Flexi-HAL
# Default stepper/servo microstepping = 2000 steps / rev for X and Y.
# Edit axis min/max limits to suit work area
# Velocities in here in units per second, not per minute.


[EMC]
MACHINE = PrintNC Flexi-HAL
;DEBUG = 0x7FFFFFFF
DEBUG = 0x0003E100
VERSION = 1.1


[DISPLAY]
DISPLAY = qtvcp -f qtdragon_hd
PROGRAM_PREFIX = ~/linuxcnc/nc_files
PREFERENCE_FILE_PATH = ~/linuxcnc/configs/printnc/qtdragon.pref
NGCGUI_SUBFILE_PATH = ~/linuxcnc/ngcgui_lib
EDITOR = geany
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = ACTUAL
ARCDIVISION = 64
GRIDS = 10mm 20mm 50mm 100mm
MAX_FEED_OVERRIDE = 2.0
MIN_SPINDLE_0_OVERRIDE = 0.5
MAX_SPINDLE_0_OVERRIDE = 2.0
DEFAULT_SPINDLE_0_SPEED = 6000
MIN_SPINDLE_0_SPEED = 1500
MAX_SPINDLE_0_SPEED = 24000
MAX_SPINDLE_POWER = 2400
DEFAULT_LINEAR_VELOCITY = 50.00
MIN_LINEAR_VELOCITY = 0
MAX_LINEAR_VELOCITY = 250.00
DEFAULT_ANGULAR_VELOCITY = 36.00
MIN_ANGULAR_VELOCITY = 0
MAX_ANGULAR_VELOCITY = 45.00
INTRO_GRAPHIC = linuxcnc.gif
INTRO_TIME = 0
INCREMENTS = 100mm 10mm 1mm 0.1mm .01mm
#Pre selected NGCGUI programs tabs, specify filenames only, files must be in the NGCGUI_SUBFILE_PATH
NGCGUI_SUBFILE = slot.ngc
NGCGUI_SUBFILE = qpocket.ngc

;EMBED_TAB_NAME = RCATC
;EMBED_TAB_COMMAND = qtvcp /home/expatria/linuxcnc/configs/printnc/qtvcp/rcatc
;EMBED_TAB_LOCATION = tabWidget_utilities

LOG_FILE = ~/linuxcnc/configs/printnc/log.log

[PROBE]
USE_PROBE = versaprobe
#USE_PROBE = basicprobe


[TOOL_CHANGE]
X = 315
Y = 0
Z = 0


[RCATC]
; bit 0: enable debug logging; bit 1: reload config on each tool change
DEBUG = 3
CONFIG_PATH = ~/linuxcnc/configs/printnc/rcatc.json


[CHANGE_POSITION]
X = 315
Y = 0
Z = 0


[VERSA_TOOLSETTER]
X = 0
Y = 0
Z = 0
MAXPROBE = 120
Z_MAX_CLEAR = 0
DIAMETER = 20


[MDI_COMMAND_LIST]
# Macro buttons, up to 10 available.
MDI_COMMAND = G53 G0 Z0;G0 X0 Y0;Z0, Goto\nUser\nZero
MDI_COMMAND = G53 G0 Z0;G53 G0 X0 Y0,Goto\nMachn\nZero


[KINS]
JOINTS = 4
KINEMATICS = trivkins coordinates=XYZY kinstype=BOTH


[FILTER]
PROGRAM_EXTENSION = .ngc,.nc,.tap G-Code file (*.ngc,*.nc,*.tap)
PROGRAM_EXTENSION = .py Python Script
py = python


[TASK]
TASK = milltask
CYCLE_TIME = 0.010


[RS274NGC]
PARAMETER_FILE = linuxcnc.var
RS274NGC_STARTUP_CODE = F10 G21 G17 G40 G49 G54 G64 P0.001 G80 G90 G91.1 G92.1 G94 G97 G98
FEATURES = 30
# on abort, this ngc file is called. required for basic/versa probe routines.
ON_ABORT_COMMAND=O <on_abort> call
REMAP = M6 modalgroup=6 prolog=change_prolog python=rcatc_tool_change epilog=change_epilog
REMAP = T prolog=prepare_prolog ngc=prepare epilog=prepare_epilog

NGCGUI_SUBFILE_PATH = ~/linuxcnc/nc_files/examples/ngcgui_lib/
SUBROUTINE_PATH = \
~/linuxcnc/nc_files/examples/ngcgui_lib:\
~/linuxcnc/nc_files/examples/ngcgui_lib/utilitysubs:\
~/linuxcnc/configs/printnc/subroutines

[PYTHON]
PATH_PREPEND = ~/linuxcnc/nc_files/python-stdglue/python
TOPLEVEL = ~/linuxcnc/nc_files/python-stdglue/python/toplevel.py
RELOAD_ON_CHANGE = 1

[EMCMOT]
EMCMOT = motmod
COMM_TIMEOUT = 1.0
COMM_WAIT = 0.010
BASE_PERIOD = 0
SERVO_PERIOD = 1000000
#SERVO_PERIOD = 500000


[HAL]
TWOPASS = on
HALFILE = remora-flexi.hal
HALFILE = xhc-whb04b-6.hal
POSTGUI_HALFILE = postgui_call_list.hal
HALUI = halui

;POSTGUI_HALFILE = rapidatc-postgui.hal

[HALUI]
MDI_COMMAND = (DEBUG,<1>)
MDI_COMMAND = G10 L20 P0 X[#<_x>/2.0]
MDI_COMMAND = G10 L20 P0 Y[#<_y>/2.0]
MDI_COMMAND = (DEBUG,<4>)
MDI_COMMAND = (DEBUG,<5>)
MDI_COMMAND = G10 L20 P0 X0
MDI_COMMAND = G10 L20 P0 Y0
MDI_COMMAND = G10 L20 P0 Z0
MDI_COMMAND = (DEBUG,<5>)
MDI_COMMAND = (DEBUG,<9>)
MDI_COMMAND = (DEBUG,<10>)
MDI_COMMAND = (DEBUG,<2>)
MDI_COMMAND = (DEBUG,<12>)
MDI_COMMAND = (DEBUG,<13>)
MDI_COMMAND = (DEBUG,<14>)


[TRAJ]
COORDINATES =  XYZY
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
CYCLE_TIME = 0.010
DEFAULT_LINEAR_VELOCITY = 50.00
MAX_LINEAR_VELOCITY = 10000.00
NO_FORCE_HOMING = 1
SPINDLES = 1


[EMCIO]
EMCIO = io
CYCLE_TIME = 0.100
TOOL_TABLE = tool.tbl


[AXIS_X]
MAX_VELOCITY = 250.0
MAX_ACCELERATION = 1500.0
MIN_LIMIT = -0.01
MAX_LIMIT = 630.0


[JOINT_0]
TYPE = LINEAR
HOME = 0.0
MIN_LIMIT = -0.01
MAX_LIMIT = 630.0
MAX_VELOCITY = 350.0
MAX_ACCELERATION = 2000.0
STEPGEN_MAXACCEL = 2000.0
P_GAIN = 50
FF1_GAIN = 1
SCALE = 200
DEADBAND = 0.005
FERROR = 5
MIN_FERROR = 0.5
HOME_OFFSET = 0.0
HOME_SEARCH_VEL = 75
HOME_LATCH_VEL = 1
HOME_FINAL_VEL = 100
HOME_USE_INDEX = NO
HOME_SEQUENCE = -1


[AXIS_Y]
MAX_VELOCITY = 250.0
MAX_ACCELERATION = 1500.0
MIN_LIMIT = -0.01
MAX_LIMIT = 628.0


[JOINT_1]
TYPE = LINEAR
HOME = 628.0
MIN_LIMIT = -0.01
MAX_LIMIT = 628.01
MAX_VELOCITY = 350.0
MAX_ACCELERATION = 3000.0
STEPGEN_MAXACCEL = 3200.0
P_GAIN = 50
FF1_GAIN = 1
SCALE = 200
DEADBAND = 0.005
FERROR = 5
MIN_FERROR = 0.5
HOME_OFFSET = 628.000
HOME_SEARCH_VEL = -75
HOME_LATCH_VEL = -1
HOME_FINAL_VEL = -2
HOME_USE_INDEX = NO
HOME_SEQUENCE = -1


[JOINT_3]
TYPE = LINEAR
HOME = 628.0
MIN_LIMIT = -0.01
MAX_LIMIT = 628.01
MAX_VELOCITY = 350.0
MAX_ACCELERATION = 3000.0
STEPGEN_MAXACCEL = 3200.0
P_GAIN = 50
FF1_GAIN = 1
SCALE = 200
DEADBAND = 0.005
FERROR = 5
MIN_FERROR = 0.5
HOME_OFFSET = 628.17085548
HOME_SEARCH_VEL = -75
HOME_LATCH_VEL = -1
HOME_FINAL_VEL = -2
HOME_USE_INDEX = NO
HOME_SEQUENCE = -1


[AXIS_Z]
MAX_VELOCITY = 100.0
MAX_ACCELERATION = 1000.0
MIN_LIMIT = -165
MAX_LIMIT = 0


[JOINT_2]
TYPE = LINEAR
HOME = 0.0
MIN_LIMIT = -165
MAX_LIMIT = 0.2
MAX_VELOCITY = 100.0
MAX_ACCELERATION = 1000.0
STEPGEN_MAXACCEL = 1200.0
P_GAIN = 10
FF1_GAIN = 1.0
SCALE = -200
DEADBAND = 0.005
FERROR = 5
MIN_FERROR = 0.5
HOME_OFFSET = 0.0
HOME_SEARCH_VEL = -10
HOME_LATCH_VEL = -2
HOME_FINAL_VEL = -1
HOME_USE_INDEX = NO
HOME_SEQUENCE = 0
